docs: add statement on KMS policy Readme.md (#137)
# Description

Add an example statement to avoid errors like "error creating KMS Key:
MalformedPolicyDocumentException: The new key policy will not allow you
to update the key policy in the future."

# Checklist

- [x] My code follows the style guidelines of the project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation